env: standard
runtime: nodejs10

# env_variables:
#     NODE_ENV: "test"

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

beta_settings:
    cloud_sql_instances: cis-565:us-central1:cis-565